import type { AggregatedCourt } from './types.js';

export const MOCK_COURTS: AggregatedCourt[] = [
  // Alpha Badminton - Egerton
  {
    club: 'alpha',
    location: 'Alpha Egerton (28 Courts)',
    locationId: '2',
    courtName: 'Court 1',
    courtId: '2-0',
    timeSlot: '9:00am–10:00am',
    status: 'available',
    price: 29,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'alpha',
    location: 'Alpha Egerton (28 Courts)',
    locationId: '2',
    courtName: 'Court 1',
    courtId: '2-0',
    timeSlot: '10:00am–11:00am',
    status: 'booked',
    price: 29,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'alpha',
    location: 'Alpha Egerton (28 Courts)',
    locationId: '2',
    courtName: 'Court 1',
    courtId: '2-0',
    timeSlot: '6:00pm–7:00pm',
    status: 'available',
    price: 38,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'alpha',
    location: 'Alpha Egerton (28 Courts)',
    locationId: '2',
    courtName: 'Court 2',
    courtId: '2-1',
    timeSlot: '9:00am–10:00am',
    status: 'booked',
    price: 29,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'alpha',
    location: 'Alpha Egerton (28 Courts)',
    locationId: '2',
    courtName: 'Court 2',
    courtId: '2-1',
    timeSlot: '5:00pm–6:00pm',
    status: 'available',
    price: 38,
    date: new Date().toISOString().split('T')[0],
  },

  // Alpha Badminton - Auburn
  {
    club: 'alpha',
    location: 'Alpha Auburn (22 Courts)',
    locationId: '3',
    courtName: 'Court 5',
    courtId: '3-4',
    timeSlot: '9:00am–10:00am',
    status: 'available',
    price: 29,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'alpha',
    location: 'Alpha Auburn (22 Courts)',
    locationId: '3',
    courtName: 'Court 5',
    courtId: '3-4',
    timeSlot: '7:00pm–8:00pm',
    status: 'available',
    price: 38,
    date: new Date().toISOString().split('T')[0],
  },

  // NBC Badminton - Silverwater
  {
    club: 'nbc',
    location: 'Silverwater',
    locationId: '1',
    courtName: 'Court 1',
    courtId: '1-0',
    timeSlot: '9:00am–10:00am',
    status: 'booked',
    price: 28,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'nbc',
    location: 'Silverwater',
    locationId: '1',
    courtName: 'Court 1',
    courtId: '1-0',
    timeSlot: '10:00am–11:00am',
    status: 'available',
    price: 28,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'nbc',
    location: 'Silverwater',
    locationId: '1',
    courtName: 'Court 2',
    courtId: '1-1',
    timeSlot: '6:00pm–7:00pm',
    status: 'available',
    price: 38,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'nbc',
    location: 'Silverwater',
    locationId: '1',
    courtName: 'Court 3',
    courtId: '1-2',
    timeSlot: '9:00am–10:00am',
    status: 'available',
    price: 28,
    date: new Date().toISOString().split('T')[0],
  },

  // NBC Badminton - Castle Hill
  {
    club: 'nbc',
    location: 'Castle Hill',
    locationId: '5',
    courtName: 'Court 1',
    courtId: '5-0',
    timeSlot: '9:00am–10:00am',
    status: 'available',
    price: 28,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'nbc',
    location: 'Castle Hill',
    locationId: '5',
    courtName: 'Court 1',
    courtId: '5-0',
    timeSlot: '10:00am–11:00am',
    status: 'booked',
    price: 28,
    date: new Date().toISOString().split('T')[0],
  },
  {
    club: 'nbc',
    location: 'Castle Hill',
    locationId: '5',
    courtName: 'Court 2',
    courtId: '5-1',
    timeSlot: '7:00pm–8:00pm',
    status: 'available',
    price: 38,
    date: new Date().toISOString().split('T')[0],
  },
];

export function getRandomMockData(): AggregatedCourt[] {
  // Return all mock data (or shuffle/filter as needed)
  return MOCK_COURTS;
}
